# -*- coding: utf-8 -*-
"""DM Proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ExV5CaGuGOyJZllZEAT6hNxu_DCvO1H

# Dataset Description

Dataset Ref: https://www.cdc.gov/brfss/annual_data/2020/pdf/codebook20_llcp-v2-508.pdf
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/DM Project/Data/heart_2020_cleaned.csv')

display(df)

df.shape

df.isnull().sum()

df['HeartDisease'].value_counts()

"""# Understanding the data"""

col_df = list(df.columns.values)
for column in col_df:
    print(column, ':', str(df[column].unique()))

"""# Exploratory Data Analysis(EDA)"""

from matplotlib import pyplot as plt
import seaborn as sns
from pandas.plotting import scatter_matrix

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
scatter_mat = scatter_matrix(df, figsize=(15, 15))

features = df.select_dtypes(include=[object])
features.columns

def feature_div():
  plt.figure(figsize = (30,20))
  i = 1
  for feature in features:
      plt.subplot(3,5,i)
      sns.set(palette='crest')
      sns.set_style("ticks")
      ax = sns.countplot(x = feature, data = df)#, hue = 'pastel')#, color='#221C35')
      #Set the x-tick labels with list of string labels
      ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right")
      i +=1
feature_div()







"""# **References:**

* https://www.cdc.gov/brfss/annual_data/2020/pdf/codebook20_llcp-v2-508.pdf
*https://digital.library.txstate.edu/bitstream/handle/10877/8132/GRITSENKO-THESIS-2019.pdf?isAllowed=y&sequence=1
"""